import { CommonTokenStream, InputStream } from "antlr4";
import { P4Lexer } from "../antlr_autogenerated/P4Lexer";
import { P4Parser } from "../antlr_autogenerated/P4Parser";
import ASTBuilderListener from "./ASTBuilderListener";
import { ParseTreeWalker } from "antlr4/tree";
import ASTNode from "./ASTNode";

export default function getAST(input: string): ASTNode {
  const chars = new InputStream(input);
  const lexer = new P4Lexer(chars);
  const tokens = new CommonTokenStream(lexer);
  const parser = new P4Parser(tokens);
  const tree = parser.program();
  const builder = new ASTBuilderListener();
  ParseTreeWalker.DEFAULT.walk(builder, tree);
  return builder.getTree();
}
