import { P4Listener } from '../antlr_autogenerated/P4Listener';
import { logDebug, logInfo} from '../utils/logger';
import { P4IRTypes } from './p4_ir_types';
import { SymbolTable } from './symbol_table';

export class MyP4Listener extends P4Listener{
	private sTable: SymbolTable;

	constructor(){
		super();
		P4Listener.call(this);
		this.sTable = new SymbolTable();
	}

	enterProgram(ctx){
		this.sTable.push(ctx, P4IRTypes.P4_PROGRAM);
	}

	exitProram(ctx){
		this.sTable.pop();
	}

	enterConstantDeclaration(ctx) {
		let name: string = ctx.name();
		let type: string = ctx.typeRef();

	}
}